# -*- coding: utf-8 -*-
"""Food Picker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V8HC9IOaCUFac470WLestOaBpC9eI-Ow

Food Picker
"""

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

df1 = pd.read_csv(r"dataset-ayam.csv")
df2 = pd.read_csv(r"dataset-ikan.csv")
df3 = pd.read_csv(r"dataset-kambing.csv")
df4 = pd.read_csv(r"dataset-sapi.csv")
df5 = pd.read_csv(r"dataset-tahu.csv")
df6 = pd.read_csv(r"dataset-telur.csv")
df7 = pd.read_csv(r"dataset-tempe.csv")
df8 = pd.read_csv(r"dataset-udang.csv")

df_list = [df1, df2, df3, df4, df5, df6, df7, df8]
df = pd.concat(df_list, ignore_index=True)
df.reset_index()
df['index'] = df.index
display(df)

cv = CountVectorizer()
count_matrix = cv.fit_transform(df["Ingredients"].values.astype('U'))
print("Count Matrix:", count_matrix.toarray())

cosine_sim = cosine_similarity(count_matrix)
cosine_sim

recipe_user_likes = "Siomay Udang Ayam"
def get_index_from_title(Title):
    return df[df.Title == Title]["index"].values[0]
recipe_index = get_index_from_title(recipe_user_likes)
recipe_index

similar_recipes = list(enumerate(cosine_sim[recipe_index]))
similar_recipes

sorted_similar_recipes = sorted(similar_recipes, key=lambda x:x[1], reverse=True)
sorted_similar_recipes

def get_title_from_index(index):
    return df[df.index == index]["Title"].values[0]
i=0
for recipe in sorted_similar_recipes:
    print(get_title_from_index(recipe[0]))
    i=i+1
    if i>10:
        break